name: esp-idf-build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout repo
      - uses: actions/checkout@v2

      # copy sdkconfig.s2usb to sdkconfig
      - name: copy-sdkconfig
        run: cp sdkconfig.s2usb sdkconfig

      # run build of project in latest esp-idf container
      - name: ESP-IDF v4.x build
        uses: CalinRadoni/esp-idf-v4-container-action@v4.1
        id: esp-idf-build

      - name: Show the exit code
        run: echo "The exit code was ${{ steps.esp-idf-build.outputs.result }}"
